on: [push]


jobs:
  environme_job:
    runs-on: ubuntu-latest
    name: EnvironMe
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Environ Me action step
        id: EnvironMe
        uses: urbanantics/environme-github-action@v0.0.0
        env:
          my_test: ${{ secrets.test }}
        with:
          path: '**/*'
      - run: ls basic/test
      - run: printenv
        env:
          my_test: ${{ secrets.test }}
